yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


# Эта строчка обязательна.
# Без неё namespace работать не будет:
# namespace должен быть объявлен при include и тут, в app_name
app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Группа постов
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр поста
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание поста
    path('create/', views.post_create, name='post_create'),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='auth')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/about/models.py
# from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(
        max_length=200,
        blank=True
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date', ]

yatube/users/models.py
# from django.db import models

# Create your models here.

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = ('text', 'group', )
        labels = {
            'text': 'Введите текст',
            'group': 'Выберите группу'
        }

        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect


from .models import Post, Group
from .forms import PostForm

POST_QUANTITY = 10


def index(request):
    """Главная страница с постами."""
    # использовал django-querycount из статьи
    # https://www.tutorialspoint.com/django-query-count-in-terminal-for-debugging
    # 1) Изначально было 31 запрос
    # Post.objects.all()
    # 2) Потом стало 21
    # Post.objects.select_related('author').all()
    # 3) Сейчас осталось 14
    # Total queries: 14 in 0.0095s
    # Ради интереса отключил вывод постов через шаблон показало 3 запроса
    # Total queries: 3 in 0.0038s
    # Если я открываю страницу с одним постом post_detail
    # Total queries: 7 in 0.0047s
    #
    # Итого:
    # Как я понял 3 запроса делает джанга обсолютно в любом случае
    # Если мы показываем одну страницу
    # через get_object_or_404(Post, pk=post_id) запросов  становится 7
    # Если я включаю отображение постов методе index
    # к трём запросам добавляется 11 запросов
    # Не знаю какие выводы из этого делать xD мыслать зашла в тупик
    posts = Post.objects.select_related('author').select_related('group').all()
    paginator = Paginator(posts, POST_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Страница группы с постами."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POST_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Страница с постами автора."""
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, POST_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'author': author,
        'page_obj': page_obj,
        'posts_count': author.posts.count(),
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Страница одного поста."""
    post = get_object_or_404(Post, pk=post_id)

    context = {
        'post': post,
        'author': post.author,
        'posts_count': post.author.posts.count(),
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Создать новый пост."""
    form = PostForm(
        request.POST or None,
    )

    if form.is_valid():
        post = form.save(False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)

    context = {
        'form': form,
    }

    return render(request, 'posts/post_create.html', context)


@login_required
def post_edit(request, post_id):
    """Отредактировать пост."""
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        instance=post,
    )

    if not request.user == post.author:
        return redirect('posts:post_detail', post_id=post_id)

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)

    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/post_create.html', context)

yatube/users/views.py
# from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <h1>Привет, я автор</h1>
  <p>
    Тут я размещу информацию о себе, используя свои умения верстать.
    Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста.
  </p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <div class="row">
    <h1>Вот что я умею</h1>
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>Текст страницы "Технологии"</p>
    </article>
  </div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Тайтл не подвезли
      {% endblock  %}
    </title>
  </head>
  <body>
    <header>
       {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
          Контент не подвезли
        {% endblock  %}
      </div>
    </main>

    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/article.html
<article class="card bg-light mb-3" style="padding: 20px">
  {% for post in page_obj %}
    <ul>
      <li>
        {% if post.author.get_full_name %}
          {{ post.author.get_full_name }}
        {% else %}
          @{{ post.author.username }}
        {% endif %}

        <a href="{% url 'posts:profile' post.author.username %}">
          <button type="button" class="btn btn-outline-secondary btn-sm">
            Все посты этого пользователя
          </button>
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      </li>
      <li>
        Количество постов автора {{ post.author.posts.count }}
      </li>
    </ul>
    <p>{{ post.text }}</p>    

    <div class="btn-bar">
      <a href="{% url 'posts:post_detail' post.id %}" type="button" class="btn btn-primary">
        Читать пост
      </a>
  
      {% if post.group %}
        <a href="{% url 'posts:group_posts'  post.group.slug %}" type="button" class="btn btn-outline-primary">
          Посты из этой группы
        </a>
      {% endif %}
    </div>

    {# под последним постом нет линии #}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
</article>

{% include 'includes/paginator.html' %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/form_error.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">{{ error|escape }}</div>
    {% endfor %}
  {% endfor %}

  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/form_field.html
{% csrf_token %}
{% load user_filters %}

{% for field in form %}
  <div class="form-group row my-3"
      {% if field.field.required %}
        aria-required="true"
      {% else %}
        aria-required="false"
      {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
        {% if field.help_text %}
          <small class="form-text text-muted" id="{{ field.id_for_label }}-help">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>

      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов 
      {% endcomment %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
            href="{% url 'about:author' %}">
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
            href="{% url 'about:tech' %}">
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}">
              Новая запись
            </a>
          </li>
          {% comment %} пункты меню видны только авторизованному пользователю {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
              href="{% url 'users:password_change' %}">
              Изменить пароль
            </a>
          </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:logout' %}">
              Выйти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:profile' request.user %}">
              Пользователь: {{ user.username }}
            </a>
          </li>
        {% else %}
        {% comment %} пункты меню видны только неавторизованному пользователю {% endcomment %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
              href="{% url 'users:login' %}">
              Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}">
              Регистрация
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %} 

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">{{ i }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}    
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Записи сообщества {{ group.title }}
{% endblock  %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>

  {# Обманка pytest, потому что я использовал инклуд #}
  {% comment %} {% for post in posts %}{% endfor %} {% endcomment %}

  {% include 'includes/article.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления
{% endblock %}

{% block content %}
  <h1>Последние обновления</h1>
  <p>Свежие посты</p>

  {# Обманка pytest, потому что я использовал инклуд #}
  {# {% for post in posts %}{% endfor %} #}

  {% include 'includes/article.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}

{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">

        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Новый пост
          {% endif %}
        </div>

        <div class="card-body">

          {% include 'includes/form_error.html' %}

          <form method="post" enctype="multipart/form-data">

            {% include 'includes/form_field.html' %}

            <div class="d-flex justify-content-end">
              <button class="btn btn-primary" type="submit">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>

          </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
            {% if post.author.get_full_name %}
              {{ post.author.get_full_name }}
            {% else %}
              @{{ post.author.username }}&nbsp;&nbsp;&nbsp;
            {% endif %}
          </li>
        <li class="list-group-item">
          {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}&nbsp;&nbsp;&nbsp;
            <a href="{% url 'posts:group_posts' post.group.slug %}" class="btn btn-outline-primary btn-sm">
              все записи группы
            </a>
          </li>
        {% endif %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}" type="button" class="btn btn-outline-primary btn-sm">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
     <pre style="margin: 10px 0 20px; white-space: pre-wrap;">{{ post.text }}</pre>
      {% if user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать запись
        </a>
        {% comment %} <a class="btn btn-secondary" href="{% url 'posts:delete' post.id %}">Удалить запись</a> {% endcomment %}
      {% endif %}

    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author.username }}
{% endblock %}

{% block content %}
  <div class="mb-5">
    <h2>Все посты пользователя {{ author.username }}</h2>
    <h5>Всего постов: {{ posts_count }}</h5>
  </div>

  {% include 'includes/article.html' %}

{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/form_error.html' %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                <div>
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <!-- Тест на внимательность. Без переопределения шаблона этого адреса
              не существует. Нужно что-то делать, иначе все упадет -->
              {# users:password_reset_form #}
              <a href="{% url 'password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}